'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TblCliente
    Public Property ID_Cliente As Nullable(Of Integer)
    Public Property Nombre_Cliente As String
    Public Property Direccion As String
    Public Property Pais As String
    Public Property FechaPedido As Nullable(Of Date)
    Public Property Cupo As Decimal

End Class
